# Shopping Dataset — Python & Pandas Week 1
**Dataset:** Myntra Shopping Dataset (Kaggle)  
**Objective:** Load, Explore, Clean, and Save using Pandas

---

## Step 1: Load CSV into a Pandas DataFrame

In [7]:
import pandas as pd

df = pd.read_csv('Combined_dataset.csv')
print('Dataset loaded successfully!')
print(f'Shape: {df.shape}')

Dataset loaded successfully!
Shape: (1000, 20)

## Step 2: Explore the Data

In [8]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,sizes,best_offer,more_offers,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue solid backpackNon-Pa...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""size"":""Onesize""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shopping_cleaned,59925
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue backpackNon-Padded h...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...","[{""size"":""Onesize""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shopping_cleaned,194233
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...","[{""size"":""S""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shopping_cleaned,677774
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...","[{""size"":""Onesize""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shopping_cleaned,1762100
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue solid bath robe, has a sh...","[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",{},"[{""offer_name"":""10% Instant Discount on IndusI...",shopping_cleaned,34788

In [9]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,sizes,best_offer,more_offers,category,total_amount
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Features:Nothing about the For...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""size"":""Onesize""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shopping_cleaned,130790
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""Onesize""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shopping_cleaned,195800
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Case style: Analogue watch, ha...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Dial Material"",""specif...","{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""size"":""Onesize""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shopping_cleaned,39750
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pack Contains: single watch D...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...","[{""size"":""Onesize""}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shopping_cleaned,56015
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: One yoga matColou...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Mat Thickness"",""specif...","{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...","[{""size"":""Medium""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shopping_cleaned,112539

In [10]:
print('Shape (rows, columns):', df.shape)
print('\nColumn names:')
print(df.columns.tolist())

Shape (rows, columns): (1000, 20)

Column names:
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'sizes', 'best_offer', 'more_offers', 'category', 'total_amount']

In [ ]:
print('Data Types:')
print(df.dtypes)

Data Types:
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

## Step 3: Handle Missing Values

In [ ]:
print('Missing values per column:')
print(df.isnull().sum())

Missing values per column:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [ ]:
# Drop columns that have too many missing values (not useful for analysis)
df.drop(columns=['videos', 'what_customers_said', 'seller_name',
                  'seller_information', 'variations'], inplace=True)

# Fill missing 'discount' with 0 (no discount)
df['discount'].fillna(0, inplace=True)

print('Missing values after handling:')
print(df.isnull().sum())

Missing values after handling:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
sizes                       0
best_offer                  0
more_offers                 0
category                    0
dtype: int64

/tmp/ipykernel_540/3630737121.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['discount'].fillna(0, inplace=True)

## Step 4: Basic Operations — Filter Rows & Select Columns

In [ ]:
# Select specific columns
selected = df[['product_id', 'title', 'category', 'rating', 'initial_price', 'discount']]
print('Selected columns:')
selected.head()

Selected columns:

   product_id           title   category  rating  initial_price  discount
0     8376765     Lino Perros  backpacks     3.8           3995      58.0
1     9136281  Tommy Hilfiger  backpacks     4.5           2899      35.0
2    17633752           Lavie  backpacks     4.4           2999      65.0
3     1376949          F Gear  backpacks     4.4           1675      52.0
4    13939916       MYTRIDENT  bath-robe     4.7           2899      17.0

In [ ]:
# Filter rows: products with rating >= 4.0
high_rated = df[df['rating'] >= 4.0]
print(f'Products with rating >= 4.0: {len(high_rated)}')
high_rated[['title', 'category', 'rating', 'initial_price']].head()

Products with rating >= 4.0: 615

            title              category  rating  initial_price
1  Tommy Hilfiger             backpacks     4.5           2899
2           Lavie             backpacks     4.4           2999
3          F Gear             backpacks     4.4           1675
4       MYTRIDENT             bath-robe     4.7           2899
5             H&M  bathroom-accessories     4.5           1399

## Step 5: Remove Duplicates

In [ ]:
print(f'Rows before removing duplicates: {len(df)}')
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)
print(f'Rows after removing duplicates : {len(df)}')

Rows before removing duplicates: 1000
Rows after removing duplicates : 1000

## Step 6: Create Derived Column — total_amount

In [ ]:
# total_amount = initial_price * ratings_count
# (price * quantity — using ratings_count as a proxy for quantity sold)
df['total_amount'] = df['initial_price'] * df['ratings_count']

print('total_amount column created:')
df[['title', 'initial_price', 'ratings_count', 'total_amount']].head()

total_amount column created:

            title  initial_price  ratings_count  total_amount
0     Lino Perros           3995             15         59925
1  Tommy Hilfiger           2899             67        194233
2           Lavie           2999            226        677774
3          F Gear           1675           1052       1762100
4       MYTRIDENT           2899             12         34788

## Step 7: Save Cleaned Dataset as New CSV

In [11]:
df.to_csv('shopping_cleaned.csv', index=False)
print('Cleaned dataset saved as shopping_cleaned.csv')
print(f'Final shape: {df.shape}')

Cleaned dataset saved as shopping_cleaned.csv
Final shape: (1000, 20)

## Brief Summary

| Step | Action | Result |
|------|--------|--------|
| 1 | Loaded CSV | 1000 rows × 24 columns |
| 2 | Explored data | head/tail, shape, columns, dtypes |
| 3 | Handled missing values | Dropped high-null columns; filled discount with 0 |
| 4 | Filtered & selected | High-rated products (rating ≥ 4.0) |
| 5 | Removed duplicates | Checked and cleaned duplicate rows |
| 6 | Created derived column | `total_amount = initial_price × ratings_count` |
| 7 | Saved cleaned CSV | `shopping_cleaned.csv` |